---
title: "Data Organization in Spreadsheets and R"
author: "Hao Ye"
institute: "Health Science Center Libraries, University of Florida"
date: "2020-06-07 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r xaringan-themer, include = FALSE, warning = FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#09274B",
  base_font_size = "32px", 
  header_h1_font_size = "2.0rem",
  header_h2_font_size = "1.5rem",
  header_h3_font_size = "1.25rem", 
  header_background_content_padding_top = "2rem", 
  header_font_google = google_font("Lato"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono"), 
  extra_css = list("p" = list("margin-block-start" = "0.5em", 
                              "margin-block-end" = "0.5em"), 
                   "ul" = list("margin-block-start" = "0.5em", 
                              "margin-block-end" = "0.5em"), 
                   "pre" = list("margin-top" = "0.5em", 
                              "margin-bottom" = "0.5em"))
)
```

class: inverse, center, middle

# Data Organization in Spreadsheets and R
## Hao Ye
## Health Science Center Libraries, University of Florida
## 2020-06-08

---

# Goals

The goal of this workshop is to provide *practical* advice for research projects:

* you can implement these tips now
* thess skills will scale
  - more complex projects
  - more collaborators

---

# Motivations

* organizing your projects and data will:
  - improve reproducibility
  - make the work more accessible for others

---

# Learning Outcomes

By the end of the workshop, participants will be able to:

* describe and apply principles for organizing and naming files and folders
* employ the concept of tidy data for structuring tabular data
* import and view tabular data in R

---
class: inverse, center, middle

# File and Folder Organization

---

# Principles for Organization

* You don't want to spend time looking for a file or a particular version.
* Using a consistent system will build up habits for storing and finding files.
* Keep all project files in a single project folder.
* Include a project README file that describes the project.
* Separate sub-folders for raw data, processed data, code, figures.

---

# General Folders I have

```
hye/
├── grants/
├── presentations_and_travels/
├── projects/
├── vitae/
└── websites/
```

---

# Example Project in R

```
portalDS/
├── analysis/
├── data/
├── figures/
├── output/
├── R/
├── README.md
└── vignettes/
```

--
* more examples in [Marwick et al. 2018 "Packaging Data Analytical Work Reproducibly Using R (and Friends)"](https://www.tandfonline.com/doi/abs/10.1080/00031305.2017.1375986)

---
class: inverse, center, middle

# Naming Things

---

# Principles

Choose file names that are:
* machine-readable
* human-readable
* plays well with default ordering

---

# Machine-Readable

* Avoid spaces, punctuation, accented characters, mixing capital and lower-case.
* Use underscore `'_'` to separate grouping levels.
* Use hyphen `'-'` to separate words within a level.

---

# Human-Readable

* Use filenames that will help you find it later.
* Use nouns for objects, use verbs for actions:
  - e.g. `load-data.R`, `mtcars_measurements.csv`

---

# Plays Well with Default Ordering

* Files are usually sorted alphabetically
  - we can make use of this!
* Left-pad with numbers to order steps in a sequence:
  - e.g. `01_load-data.R`, `02_process-data.R`
* Use ISO-8601 for dates:
  - `YYYY-MM-DD` format (when files are sorted alphabetically, this format makes the order chronological, too!)

---

# Examples


---
class: inverse, center, middle

# Naming Things

---

---

class: center, middle

# Thanks!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).
